---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cover letter

Dr Thiyanga S. Talagala

Department of Statistics

University of Sri Jayewardenepura

Gangodawila, Nugegoda

Sri Lanka

\vspace{0.5cm}

Editor-in-Chief: Edwin Hancock

Pattern Recognition

13 June 2021

\vspace{1cm}

Dear Editor


\vspace{0.2cm}

We are pleased to submit the paper "Computer-aided Interpretable Features for Leaf Image Classification" for consideration for publication in the Pattern Recognition. In this manuscript, we present a set of interpretable features that can be used for image leaves recognition. This manuscript has not been published and is not under consideration for publication elsewhere. We have no conflicts of interest to disclose.

The authorship order is as follows:

The first author is: Jayani P. G. Lakshika

The second author and the corresponding author is: Thiyanga S. Talagala

Thank you for your consideration.

\vspace{0.2cm}


Sincerely, 

Jayani P. G. Lakshika

Thiyanga S. Talagala^[Corresponding Author]
