---
title: "Scagnostic_EDA"
author: "Jayani Lakshika"
date: "July 25, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(packrat)
library(tidyverse)
library(here)
library(binostics)
```

```{r}
here::here()
```

<!--create a list of the files from the target directory-->
```{r}
path <- "C:/Users/j/Desktop/Final Research/Coding/Python_codes/Flavia_Analysis/New_approach/df_polar_contour"

file_list <- list.files(path)
file_list
length(file_list)
typeof(file_list)
```

<!--To intialize a blank data frame-->
<!--To initialize column names of the dataframe-->
```{r}
data_scagnostics <- data_frame()

for (i in 1:length(file_list)){
  df_polar_im <- read.csv(paste(path,file_list[i], sep = "/"), header = TRUE)
  tem_data <- cbind(i,scagnostics(df_polar_im)[1],scagnostics(df_polar_im)[2],scagnostics(df_polar_im)[3],scagnostics(df_polar_im)[4],scagnostics(df_polar_im)[5],scagnostics(df_polar_im)[6],scagnostics(df_polar_im)[7],scagnostics(df_polar_im)[8],scagnostics(df_polar_im)[9])
  data_scagnostics <- rbind(data_scagnostics,tem_data)
}

head(data_scagnostics,10)

colnames(data_scagnostics) <- c("id","Outlying_polar","Skewed_polar","Clumpy_polar","Sparse_polar","Striated_polar","Convex_polar","Skinny_polar","Stringy_polar","Monotonic_polar")
head(data_scagnostics,10)
```



```{r}
path1 <- "C:/Users/j/Desktop/Final Research/Coding/Python_codes/Flavia_Analysis/New_approach/df_contour" 

file_list1 <- list.files(path1)

data_scagnostics_1 <- data_frame()

for (i in 1:length(file_list1)){
  df_contour_im <- read.csv(paste(path1,file_list1[i], sep = "/"), header = TRUE)
  tem_data <- cbind(i,scagnostics(df_contour_im)[1],scagnostics(df_contour_im)[2],scagnostics(df_contour_im)[3],scagnostics(df_contour_im)[4],scagnostics(df_contour_im)[5],scagnostics(df_contour_im)[6],scagnostics(df_contour_im)[7],scagnostics(df_contour_im)[8],scagnostics(df_contour_im)[9])
  data_scagnostics_1 <- rbind(data_scagnostics_1,tem_data)
}
head(data_scagnostics_1,10)

colnames(data_scagnostics_1) <- c("id","Outlying_contour","Skewed_contour","Clumpy_contour","Sparse_contour","Striated_contour","Convex_contour","Skinny_contour","Stringy_contour","Monotonic_contour")
head(data_scagnostics_1,10)

data_scagnostics <- cbind(data_scagnostics,data_scagnostics_1[,2:10])
```

<!--write.csv(data_scagnostics,"C:/Users/j/Desktop/Final--> <!--Research/Coding/Python_codes/data_scagnostics.csv", row.names = FALSE)-->

<!--create a list of the files from the target directory-->
```{r}
path3 <- "C:/Users/j/Desktop/Final Research/Coding/Python_codes/Flavia_Analysis/New_approach/df_polar_contour_maxima"
file_list_max <- list.files(path3)
file_list_max
length(file_list_max)
head(data_scagnostics,5)
No_of_max_ponits <-c()
for (i in 1:length(file_list_max)){
  df_polar_max_im <- read.csv(paste(path3,file_list_max[i], sep = "/"), header = TRUE)
  No_of_max_ponits[i] <- nrow(df_polar_max_im)
}

No_of_max_ponits
length(No_of_max_ponits)
data_scagnostics <- cbind(data_scagnostics, No_of_max_ponits)
head(data_scagnostics,5)
```
<!--create a list of the files from the target directory-->

```{r}
path4 <- "C:/Users/j/Desktop/Final Research/Coding/Python_codes/Flavia_Analysis/New_approach/df_polar_contour_minima"

file_list_min <- list.files(path4)
file_list_min
length(file_list_min)
No_of_min_points <-c()
for (i in 1:length(file_list_min)){
  df_polar_min_im <- read.csv(paste(path4,file_list_min[i], sep = "/"), header = TRUE)
  No_of_min_points[i] <- nrow(df_polar_min_im)
}

No_of_min_points
length(No_of_min_points)
data_scagnostics <- cbind(data_scagnostics, No_of_min_points)
head(data_scagnostics,5)

write.csv(data_scagnostics,"C:/Users/j/Desktop/Final Research/Coding/Python_codes/Flavia_Analysis/New_approach/data_scagnostics_with_min_max_points.csv", row.names = FALSE)

```

<!--write.csv(data_scagnostics,"C:/Users/j/Desktop/Final--> <!--Research/Coding/Python_codes/data_scagnostics_with_min_max_points.csv", row.names = FALSE)-->