---
title: "PCA_for_Scognastic"
author: "Jayani Lakshika"
date: "July 29, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, comment=NA, message=FALSE, warning=FALSE}
library(packrat)
library(tidyverse)
library(here)
library(Rtsne)
```


# Swedish Dataset

## PCA projection 
```{r, comment=NA, message=FALSE, warning=FALSE}
calculate_pca <- function(feature_dataset){
  pcaY_cal <- prcomp(feature_dataset, center = TRUE, scale = TRUE)
  PCAresults <- data.frame(PC1 = pcaY_cal$x[, 1], 
                           PC2 = pcaY_cal$x[, 2], 
                           PC3 = pcaY_cal$x[, 3],
                           PC4 = pcaY_cal$x[, 4],
                           PC5 = pcaY_cal$x[, 5])
  return(list(prcomp_out =pcaY_cal,pca_components = PCAresults))
}

pca_projection <- function(prcomp_out, data_to_project){
  
  PCA <- scale(data_to_project, prcomp_out$center, prcomp_out$scale) %*% prcomp_out$rotation
  pca_projected <- data.frame(PC1=PCA[,1], PC2=PCA[,2], PC3=PCA[,3]) 
  return(pca_projected)
  
}

data_new <- read.csv("data_all_with_label.csv", header = TRUE)

features <- data_new[, c(3:10,12:53)] # remove Outlying_polar and Outlying_contour
head(features)
pca_ref_calc <- calculate_pca(features)
# combine features and PCs' into a one dataframe
data_new$PC1 <- pca_ref_calc$pca_components$PC1
data_new$PC2 <- pca_ref_calc$pca_components$PC2
data_new$PC3 <- pca_ref_calc$pca_components$PC3
data_new$PC4 <- pca_ref_calc$pca_components$PC4
data_new$PC5 <- pca_ref_calc$pca_components$PC5
head(data_new)

ggplot(data_new,aes(x=PC1,y=PC2, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC1,y=PC3, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC2,y=PC3, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC1,y=PC4, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC1,y=PC5, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC2,y=PC4, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC2,y=PC5, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC3,y=PC4, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC3,y=PC5, col=Shape_label)) + 
  geom_point() +coord_equal()
```

## tSNE projection 

```{r, comment=NA, message=FALSE, warning=FALSE}


tsne <- Rtsne(data_new[, c(3:10,12:53)], dim = 2, perplexity = 100, verbose = TRUE, max_iter = 5000, eta = 2000)

tsne_plot <- data.frame(x = tsne$Y[,1], y = tsne$Y[,2], col = data_new$Shape_label)
ggplot(tsne_plot) + geom_point(aes(x=x, y=y, color = col)) + coord_equal()  

```



# Flavia Dataset

## PCA projection 
```{r, comment=NA, message=FALSE, warning=FALSE}

data_new <- read.csv("data_all_with_label_flavia.csv", header = TRUE)

features <- data_new[, c(3:10,12:53)] # remove Outlying_polar and Outlying_contour
head(features)
pca_ref_calc <- calculate_pca(features)
# combine features and PCs' into a one dataframe
data_new$PC1 <- pca_ref_calc$pca_components$PC1
data_new$PC2 <- pca_ref_calc$pca_components$PC2
data_new$PC3 <- pca_ref_calc$pca_components$PC3
data_new$PC4 <- pca_ref_calc$pca_components$PC4
data_new$PC5 <- pca_ref_calc$pca_components$PC5
head(data_new)

ggplot(data_new,aes(x=PC1,y=PC2, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC1,y=PC3, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC2,y=PC3, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC1,y=PC4, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC1,y=PC5, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC2,y=PC4, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC2,y=PC5, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC3,y=PC4, col=Shape_label)) + 
  geom_point() +coord_equal()

ggplot(data_new,aes(x=PC3,y=PC5, col=Shape_label)) + 
  geom_point() +coord_equal()
```

## tSNE projection 

```{r, comment=NA, message=FALSE, warning=FALSE}


tsne <- Rtsne(data_new[, c(3:10,12:53)], dim = 2, perplexity = 100, verbose = TRUE, max_iter = 5000, eta = 2000)

tsne_plot <- data.frame(x = tsne$Y[,1], y = tsne$Y[,2], col = data_new$Shape_label)
ggplot(tsne_plot) + geom_point(aes(x=x, y=y, color = col)) + coord_equal()  

```

